_wandb:
    value:
        cli_version: 0.18.3
        m: []
        python_version: 3.11.0
        t:
            "1":
                - 55
            "2":
                - 55
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
                - 61
            "4": 3.11.0
            "5": 0.18.3
            "8":
                - 3
                - 8
            "12": 0.18.3
            "13": windows-amd64
architecture:
    value: CNN
dataset:
    value: CIFAR-100
dropout:
    value: 0.2
learning_rate:
    value: 0.01
